data_path:
  train_data: D:/Academia/Learning/GreyAtom/ml_deployment_oct2017/ml_deployment_oct2017/gatut1909/data/train/article1.txt
  test_data:  D:/Academia/Learning/GreyAtom/ml_deployment_oct2017/ml_deployment_oct2017/gatut1909/data/test/article1.txt
sentence_num: 2